### ISSUE TITLE
Support for Grafana v11.0

### ISSUE THREAD

**Issue by thyland-nasuni** [grafana-toolbox/grafana-client#177]
**Describe the bug**
When trying to use the lib for Grafana v11, I keep getting authorisation errors.
```python
  File "/opt/test_project/venv/lib/python3.11/site-packages/test_project/initializers/grafana_initializer.py", line 188, in _is_postgres_datasource_created
    self._grafana_api.datasource.get_datasource_by_uid('postgres')
  File "/opt/test_project/venv/lib/python3.11/site-packages/grafana_client/elements/datasource.py", line 83, in get_datasource_by_uid
    r = self.client.GET(get_datasource_path)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/test_project/venv/lib/python3.11/site-packages/grafana_client/client.py", line 165, in __request_runner
    raise GrafanaUnauthorizedError(response)
``` 

**To Reproduce**
1. Have Grafana v11 installed
2. Create GrafanaAPI instance in the code
3. Call grafana_api_instance.datasource.get_datasource_by_uid('postgres')
4. GrafanaUnauthorizedError occurs

**Expected behavior**
Expected to not throw error
Same code worked fine against Grafana v10

**Versions**
- Grafana: [ 11 ]
- `grafana-client`: [ 4.1.0 ]
- Authentication: [Basic]

**Additional context**

**Comment by amotl** [comment]
Hi there, and thank you for writing in and reporting this flaw. Can you share your code how you are authenticating to your Grafana instance, so it may give us some clues where things may go south, in order to find out about whether it's a flaw in the library, or a configuration error.

**Comment by thyland-nasuni** [comment]
Hey,

After more debugging, it seems the issue was related to a config bug we had so its working fine for us now. Will be closing this issue.

Thanks for the help!
