### ISSUE TITLE
Updating Grafana version to Grafana v11.3.0-75420.patch2-75797 breaks the code

### ISSUE THREAD

**Issue by Zhuse** [grafana-toolbox/grafana-client#182]
**Describe the bug**

After updating our Grafana version to v11.3.0-75420.patch2-75797, verlib2 throws in InvalidVersion exception trying to parse it:

`File "/home/airflow/.local/lib/python3.7/site-packages/grafana_client/elements/datasource.py", line 378, in smartquery
    elif datasource_type in ("prometheus", "loki") and Version(self.api.version) <= VERSION_7:
  File "/home/airflow/.local/lib/python3.7/site-packages/verlib2/version.py", line 200, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")`

**To Reproduce**
1. Call `grafana_client.datasource.smartquery` on a Grafana server deployed with a patch version.

**Expected behavior**
Any deployed Grafana versions should be sanitized prior to parsing with verlib2.

**Versions**
- Grafana: [11.3.0-75420.patch2-75797]
- `grafana-client`: [ 3.11.0]
- Authentication: [Token]

**Comment by amotl** [comment]
grafana-client 4.1.2, just published to PyPI, may improve the situation for you.

**Comment by Zhuse** [comment]
Appreciate it!
